# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# This workflow builds/tests the source code. Intention is to be ran on pull requests, and required to pass before merging.
name: timr-ci
on:
  pull_request_target:    
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #node-version: [14.x, 16.x, 18.x] Can be used like this to be triggered for each version
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        cd src
        npm install
        npm run build
        npm run test